version: 2
jobs:
  build:
    docker:
      - image: clojure:lein-alpine
      - image: memcached:alpine
    steps:
      - checkout
      - restore_cache:
          key: ring-venturi-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          key: ring-venturi-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - run: lein spec
    working_directory: ~/ring-venturi
